server {
    listen 80;
    root /usr/share/nginx/html;

    location ~* \.(?:css|js|woff2?|eot|ttf|svg|png|jpe?g|gif)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}